### ISSUE TITLE
Add minimal documentation

### ISSUE THREAD

**Issue by ftoledo** [mercury0x000d/NightKernel#2]
Please, add some docs for build use and replace the stock Freedos kernel, for this.
thanks!

**Comment by m44rtn** [comment]
Hi! So, as a clarification do you mean docs for describing how to build or anything like that and how to replace the FreeDOS kernel?

Thanks

**Comment by m44rtn** [comment]
As a quick update we are currently working on this. We will keep you up-to-date.

**Comment by mercury0x000d** [comment]
The most recent commit (build 0.13) contains the new Night Kernel Reference Manual which illustrates how to build and run the kernel.

I will warn the OP, however, that the Night Kernel is a work in progress and as such is not yet ready to run DOS programs.
