### ISSUE TITLE
fdpp, 64bit freedos drop-in replacement

### ISSUE THREAD

**Issue by stsp** [mercury0x000d/NightKernel#3]
Hi guys!

Sorry if this is an off-topic here.
Just wanted to show you my small project:
https://github.com/stsp/fdpp
Its a drop-in freedos replacement working in 64bit.
Why I show it here?
Well, my project is self-contained as
it uses dosemu2 as a host platform,
which also I write. But now as fdpp became
quite stable (I'll soon make a stable release),
I am thinking about extending its scope past
dosemu2 host platform. And for that I would
need a DOS-oriented ring-0 kernel.
And this is exactly what you seem to have.
I also looked at your project goals, and it says
`full 32-bit drop-in replacement for the original 16-bit kernel of the FreeDOS
operating system`,
but so far you don't seem to have any freedos-related
code. And this is exactly what I have, and its stable.
So I thought if we merge our projects, then
you'll get the freedos replacement code instantly,
and I will get a new host platform (but of
course my primary host platform will remain
dosemu2). Additionally I can offer you a good
32bit command.com:
https://github.com/stsp/comcom32
I will be porting it to 64bit for my projects, but
you can use the 32bit version.
Let me know if you are interested in the above
developments.

Thanks!

**Comment by m44rtn** [comment]
Hi!

We made the decision not to merge projects, as we believe that would be outside the scope of our project. However, our project is released under the GPL v3 license and you can use the source as long as you meet the requirements of this license.

In the future we may use your command.com. 

Thank you for your interest,
Maarten

**Comment by stsp** [comment]
> We made the decision not to merge projects, as we believe that would be outside the scope of our project.

Could you please clarify why is it outside of the project's scope?
I want to document all the related projects in my readme file, so
I'd like to understand the goals of other projects, if possible.
I thought the 64bit (or 32bit) freedos replacement is exactly what
you aim for. So as my understanding appears wrong, could you
please clarify?
If you made that decision in the public MLs, then I suppose the
URL would be enough for me to get the clue.

**Comment by stsp** [comment]
I've found some MLs here:
https://groups.google.com/forum/?hl=en#!forum/night-dos-kernel
But it seems the decision was not done there, or I can't find it.
Puzzled.

**Comment by m44rtn** [comment]
No, you're right. The decision was made off mailing list between the founder and me. You can find the start of the discussion itself under the subject Feedback & Issues. I'll try to get some answers, this may take a while though. (I'll re-open the Issue)

**Comment by stsp** [comment]
OK, found it, thanks.
Well, this wasn't a "request for merging".
Just an offer for considerations and ideas.
Request is something that only one side wants,
and here I thought we can benefit to each other. :)
So maybe if you take it not as a request, the outcome
will be different too. I was just pondering the grounds.

**Comment by stsp** [comment]
> He offered a 32-bit command.com which you can find in his request which is linked below. Maybe I
> misunderstood the meaning of 'merge our projects'. Both projects are open source, if he wanted he
> could use our code and we could use his...
> I think we shouldn't

So it would be nice if you clarify the last sentence a
bit, as to why do you think so. Information always helps.

**Comment by m44rtn** [comment]
I didn't mean to upset you (and I'd certainly do not want to argue) and maybe I understoond it wrong. Anyway, we can benefit from each other, we're both open source. As for feedback or considerations, we love that.

The way I took your feedback, was that you may wanted our projects to become one, single project, as 'to merge' means. So, in that perspective, we both have different goals: We want to be Assembly only and we aim to be a 'bare-metal' kernel (while you, as I understood, requires dosemu2). And because we have different goals, I thought it wouldn't be a good idea to become one project (because this could complicate things and all that kind of stuff). Also, we are still very much in dev.

And why I wrote about a request: Requesting, as Google tells me means 'To politely ask for <insert>'.

**Comment by mercury0x000d** [comment]
Hi stsp, and thanks for the interest.

How exactly does your project differ from DOSEmu2? As I read it, you extended DOSEmu2 to be a 64 bit application instead of 32, yes? Our kernel isn't to the 64-bit level (yet) so I that's what drove the conclusion on my part that your project is outside the scope of ours. Also, we are aiming to run on a bare CPU and not under an emulation layer of any sort.

That's not to say that what you did isn't useful; getting 16-bit code to run under a 64-bit host is very nice indeed, just not something we need at this point.

If I have misread something here, feel free to clarify/correct as necessary. :)

**Comment by stsp** [comment]
> The way I took your feedback, was that you may wanted our projects to become one,
> single project, as 'to merge' means.

Yes, this part was not properly explained by me.
What I meant by "merge" is to produce a product
that includes both project. I.e. there may be a
freedos-3.14 that consists of NightKernel and
fdpp running on top. So I didn't mean a merge in
terms of the source code. Source code should
remain separate, but every project can be prepared
to work together with another one, and then someone
will be able to create a single product from those 2.

> How exactly does your project differ from DOSEmu2?

dosemu2 is my project, I started it and I maintain it. :)
But the project in question is fdpp - its my new development.
dosemu2 is a host platform that can run any DOS.
Its a virtual machine, like qemu etc. Traditionally it was
running freedos. But now I am switching it to fdpp (of
course running freedos and all other doses will still
be supported).

fdpp is not dosemu2 and has no affiliations to it other
than it can run on top of it as any other dos could.
fdpp is a 64bit freedos. Literally. I mean, I took virgin
freedos sources and wrote a 64bit meta-compiler for
them. This is what fdpp is. The readme on the github
page states this all.
So fdpp is exactly and literally a drop-in freedos
replacement. It can be compiled in 32bit too, even
if I usually compile it for 64bit. It can't be compiled
in 16bits right now, but even that possibility is not
impossible in the future (but freedos itself is compiled
in 16bits so I don't see a big benefit in adding a 16bit
target).
If we run fdpp on NightKernel instead of on dosemu2,
than the goals of your project are suddenly fully
achieved! All the work is already done, its just a
matter of making NightKernel a host platform for
fdpp, and you have a full-blown 64bit freeDOS.
This is what I wanted to point out. :)

**Comment by stsp** [comment]
> Also, we are aiming to run on a bare CPU and not under an emulation layer of any sort.

Yes, that's the point.
Running on dosemu2 is cool, but running
on NightKernel (i.e. on bare metal) is also cool.
I think fdpp will benefit from running on bare
metal, but it can do so only if NightKernel allows.
I added the fdpp support to dosemu2, and it was
just about 100 lines of code. Adding the support
to NightKernel may be more difficult, but still 100000
times simpler than writing the DOS compatibility
layer from zero.

**Comment by stsp** [comment]
> We want to be Assembly only and we aim to be a 'bare-metal' kernel (while you,
> as I understood, requires dosemu2).

This is true, but there are no dependencies on dosemu2.
I wrote fdpp in a portable way. Its just that I wrote also a
small stubs on dosemu2 side to support fdpp. NightKernel
can also add fdpp support, if you find that idea interesting.

**Comment by stsp** [comment]
> We want to be Assembly only

You mean the kernel is assembly-only, or also the
user-space part is assembly-only? If also the user-space
part is assembly-only, then indeed this defeats the
entire purpose of fdpp... But then may I ask why to
limit the user-space to assembly-only? :)

**Comment by stsp** [comment]
> duplicating DOS command in 32/64 bit environment isn't really a need per se,
> every OS has commands like copy, move, format, fdisk, fsck (or chkdsk)...'

This is a misunderstanding. I offered a 32bit command.com,
but it have nothing to do with fdpp, its just yet another development.
fdpp is not about DOS commands, its about DOS itself - exactly
what NoghtKernel needs. Its not in asm (fortunately), but its not
a ring-0 part of the kernel, its a ring-3 appl. I hope you will allow
the ring-3 apps to be written not only in asm. :)

**Comment by stsp** [comment]
If what I say is not quite clear, this may be because
I assume the resemblance between NightKernel and
freedos-32 kernel. freedos-32 kernel had a big userspace
part where they aimed to build the DOS compatibility layer.
I wasn't in time with fdpp there, and now freedos-32 project
is defunct. I don't know the architecture of NoghtKernel, and
maybe it is less suitable for fdpp than freedos-32 was.
But what I ask you about, is just to evaluate the possibility.
You can write the DOS compatibility layer from zero, or
you can take a working one - fdpp.

**Comment by stsp** [comment]
Also writing a DOS compatibility layer from zero
will never be a drop-in freedos replacement. Its a
very difficult goal. I have a drop-in freedos replacement
exactly because I developed the way to compile the
freedos itself (freedos kernel itself, not its commands
or whatever) in 64bits.

**Comment by stsp** [comment]
OK, perhaps the term "64bit DOS" is too
vague and suggests I am offering you a
64bit commands, like xcopy etc. In this case
let me briefly summarize what exactly will
you gain by adopting fdpp:
- block device layer (hdd)
- fat fs
- char device layer (console)
- UMB/HMA support
- network redirector for remote drives
- int21 API wrapping all the above, and more.

You can write this all from scratches, but I
don't believe it will be a freedos replacement.
Its too difficult to write a freedos replacement
without using the freedos sources. And I really
don't think anyone else will ever offer you a
64bit port of freedos sources, as this is considered
impossible by the freedos developers themselves.
So don't let the ideas be wasted just because
of the scepticism. I am very well aware you
don't believe the random github guy can offer
something useful. But life is full of surprises.
I have a 64bit DOS working, and nobody else
does, despite many attempts in the past.
Oh well, I lied: dosbox guys managed to do
that too, but its not portable, you can't easily
rip off the DOS from dosbox and put it to
NightKernel. With fdpp you can do just that.

**Comment by mercury0x000d** [comment]
I see, so instead of merging code bases it would be more like writing code with each other in mind. That's a much more likely possibility than a complete merge of both projects lol

Ah, I didn't realize dosemu2 was your project. So it could be likened to VirtualBox, then? And fdpp would be the guest OS running atop it? That makes sense, but if that's the case I'm just curious why dosemu2 and fdpp (or, for that matter, Night and fdpp) need to be made aware of each other to run properly. E.g., operating systems need not be compiled with VirtualBox support to run on VirtualBox.

As the group greeting lays out, the Night kernel is just that - a kernel only; there are zero user space components. The kernel itself is written in pure x86 Assembly, and by design duplicates solely the functionality of the FreeDOS file _kernel.sys_, except in 32-bit protected mode. Applications may be written in whatever language the author sees fit, however; fine tuned Assembly is only required for the kernel itself.

Night is vastly different from FreeDOS-32, which aimed (as of the last time I looked into the project, at least) to recreate most of the DOS environment in 32-bit (e.g. incompatible with the original) code.

So far as the DOS API, I agree using ready-made code would be easier than writing from scratch, but if fdpp is literally a 64-bit compile of existing FreeDOS sources (which is what we're planning to use anyway) then what do we gain exactly by using your source over the original FreeDOS code? Also, neither is written in Assembly, so using either will equally entail us gleaning what we can procedurally and reimplementing the logic in Assembly.

It seems we already have working a good portion of the six features in your summary, or at least the code to power them at a lower level. I recently completed ATA and ATAPI disk access (block driver), a FAT family driver is already well underway, we have the underlying code to power the console with the ability to print and scroll text, and the rest will be implemented by the original DOS applications themselves: memory management for DOS apps should be able to be handled initially by existing drivers (_himem,sys_, etc.) and network functionality and redirection will be handled by existing tools. We're just providing them a more modern base platform on which to run.

All that being said, don't interpret my questions/responses as me raining on your parade! To the contrary, I see potential here and I think we're all a bit curious how fdpp would possibly fit in with the way in which we've already structured Night. I think some cross-usage of code will be beneficial to both projects (particularly once we're actually ready to implement the DOS API) and the collaborative features of GitHub should facilitate this nicely.

**Comment by stsp** [comment]
> I see, so instead of merging code bases it would be more like writing code with each other in mind.

Indeed. By merging I meant creating a new
product like FreeDOS-3.14 or whatever, that
will consist of both projects (thus forming a
merge of them), but the projects itself are still
independent.

> Ah, I didn't realize dosemu2 was your project. So it could be likened to VirtualBox, then?

What do you mean?
dosemu2 is an emulator on its own, it
doesn't need VirtualBox. Maybe you mean
fdpp can be linked to VirtualBox? So far this
is not the case, But NightKernel may allow
this to happen.

> And fdpp would be the guest OS running atop it?

Yes, and this already works and is already
used by beta-testers. I didn't yet made any
dosemu2 release where fdpp is a default guest
OS, but this is inevitable.

> I'm just curious why dosemu2 and fdpp (or, for that matter, Night and fdpp)
> need to be made aware of each other to run properly. E.g., operating systems
> need not be compiled with VirtualBox support to run on VirtualBox.

Because fdpp is a user-space 64bit component,
whereas original freedos is a realmode component.
64bit DOS userspace needs an OS-specific v86
access, and fdpp is portable, so it doesn't use any
OS-specific APIs. Therefore it provides the callback
structure that the host app have to fill in, giving it
an access to v86 services. Also various logging/debugging
features are provided via call-backs to allow the
host app to manage the fdpp logging.
So overall the dependency on a host app is very
small, but its there and its unavoidable.
In fact this is summarized in the project's readme.
Basically I've already told everything, but readme
also refers to the code example, so you can still
read it.
So fdpp itself is not self-contained, but fdpp+NightKernel
may be a self-contained combination. fdpp+dosemu2
is also a self-contained combination, but its not a
bare-metal OS in that case.

> Night is vastly different from FreeDOS-32, which aimed (as of the last time I looked
> into the project, at least) to recreate most of the DOS environment in 32-bit (e.g.
> incompatible with the original) code.

So from this description I don't see a difference
between freedos-32 and NightKernel. I guess this
is somewhere in "most of the DOS environment in 32-bit"
vs "solely the functionality of the FreeDOS file kernel.sys, except in 32-bit protected mode",
but I am not sure I understand the difference.
But if you don't have the kernel/user split, the
way freedos-32 had, then that's a big difference,
and a big (fatal?) problem for fdpp adoption indeed.
fdpp is exactly the port of kernel.sys. I am porting
other components, like command.com, independently,
not as part of fdpp. In fact, after porting command.com
I'll stop. I want only the essential components to work
in 64bit, with the rest working in v86.

> So far as the DOS API, I agree using ready-made code would be easier than
> writing from scratch, but if fdpp is literally a 64-bit compile of existing FreeDOS
> sources (which is what we're planning to use anyway) then what do we gain exactly
> by using your source over the original FreeDOS code?

This is the most interesting part, and I am really confused here.
You were saying you only use asm and no kernel/user split.
How can you then use the original freedos source code in C?
And you seem to be saying you are going to compile the
original freedos C sources in 32bits? Could you please elaborate?
How? With what compiler? Wtf? :) I don't understand.

> Also, neither is written in Assembly, so using either will equally entail us gleaning
> what we can procedurally and reimplementing the logic in Assembly.

Ah, so is your plan to get the freedos C sources,
and somehow recreate them in a 32bit asm by hands?
Without using any compiler at all? OK, if that's the case,
then indeed you gain absolutely zero by using the fdpp
sources. fdpp is about compiling freedos for 32 or 64bit
environments, and if you can do that work by hands, rather
than by the use of an fdpp tool-chain, then I'd say you don't
need fdpp at all. :) But let me remind you that freedos sources
(only kernel.sys!) are around 1Mb in their size. So its never
too late to change the plans. :) But of course I am not in a
position of asking you to please turn yourself into a freedos-32
kernel. I just somehow thought they are similar, and that was
the main misunderstanding.

> and network functionality and redirection will be handled by existing tools.

Just to clarify, DOS kernel itself should include the network
redirector client. If its support is not there, the external tools
can't help. This is why I mentioned it in the feature list, but
of course you may be able to implement it as any other components.

> All that being said, don't interpret my questions/responses as me raining on your parade!

Don't get me wrong, I am just pondering grounds within
different projects. A good discussion with the reasoning
"why not" is well sufficient. Plain "we are not interested"
is less sufficient, but we are already well past that stage. :)
Understanding of other project's goals will help me to
write the proper documentation with explanations why
it is not possible to do this and that (like, why I didn't create
the bare-metal boot with the help of NightKernel etc).

**Comment by stsp** [comment]
> Indeed. By merging I meant creating a new
> product like FreeDOS-3.14 or whatever, that
> will consist of both projects (thus forming a
> merge of them),

Which means a merge only in a binary form.
I should have used the word "linking", but I
know NightKernel doesn't support the dynamic
linking, shared libraries and all that. So I
imagined the scenario where the build system
is created that can build both projects together.
In that case someone who builds the final product,
will need to download both sources, merge them
locally and then build. Such a "merge" can be
achieved for example by the use of git submodule
mechanism.
Just trying to clarify why I used the "merge" term. :)

**Comment by stsp** [comment]
> So... What's the plan? Keep denying

Let me note that this is a bit strange attitude. :)

> and point him to the fork feature?

... of the freedos-32 kernel, as a matter of fact.
Just to note and to not violate anyone's copyrights,
the comcom32 project was derived from freedos-32
repository too. But I am not in such a bad need of a
new host platform, as to also resurrect their kernel...

**Comment by stsp** [comment]
I don't mind any opinions (as to wanting
someone to stop), and I think Mercury already
explained most of the things he had to.
So unless I am misunderstanding the idea
of manually translating the original freedos
sources to asm (and of course I suppose you
estimated and realize the needed efforts),
the only possibility for a [ merge | integration | linking | whatever ]
is to change the NightKernel goals towards
the kernel/user split. Which is unlikely to happen,
as I understand it now.
Let me just offer a bit of rough numbers.
Freedos sources are 1Mb. Writing an fdpp
tool-chain for it was about writing only 100Kb
of code. So the win was around 10 times than
writing everything from scratches in C. And
stabilizing the tool-chain was probably yet 10
times simpler than stabilizing the freshly written
in C DOS kernel.
Now if you translate the 1Mb of freedos sources
to asm by hands, this is going to be, how much?
5Mb? 10Mb of hand-written asm? I don't know. :)

**Comment by stsp** [comment]
> Let me just offer a bit of rough numbers.

So by that I just wanted to point out that
the manual translation may not be a time-saving
approach, while fdpp - is, even if it is written
from scratches (only 100Kb of code). And given
that it is _already_ written, the cost is zero, while
the manual translation may be even more difficult
than rewriting the entire freedos from scratches in C.

**Comment by cuzintone** [comment]
Ok, 
 
Here's the idea (at least in the original plan), NightKernel provides a kernel that boots in place of the FreeDOS kernel. It brings along with it a VM service (among other things) that translates the existing DOS API into NightKernel (like what would happen if DOS is run under OS/2) Obviously character mode calls using the DOS API (Int 21h/01-0B or so (IIRC) would just translate to the NightKernel Console. the VM would trap Int 10h calls and virtualize direct writes to video memory. No actual FreeDOS code would be moved between the environment as it is not needed.

**Comment by cuzintone** [comment]
Also,

In this 64-bit DOS environment, will applications like WordPerfect 5.1, Lotus 1-2-3 2.x, dBase IV function as they should? No one is writing new DOS applications, so the barometer on functionality will be these old quirky programs that run as though they own the whole machine

**Comment by stsp** [comment]
> No actual FreeDOS code would be moved between the environment as it is not needed.

OK, I hear you, but this doesn't look similar to what
was written by @mercury0x000d, which was
`but if fdpp is literally a 64-bit compile of existing FreeDOS sources (which is what we're planning to use anyway) then what do we gain exactly by using your source over the original FreeDOS code?`

I guess the lack of the architecture documentation brings
in the confusion. I don't know who of yours says true and
who is not.
Also if you do it the way you say, I wonder why do you
think it will be a drop-in freedos replacement. Achieving
a drop-in compatibility w/o using actual freedos sources
is IMHO a nearly impossible task. So at least maybe you
should remove the "drop-in freedos replacement" part from
your docs and just say you are writing a new DOS. If it
would be that way in the docs, I wouldn't be confused to
offer you a real drop-in replacement. :)

> In this 64-bit DOS environment, will applications like WordPerfect 5.1,
> Lotus 1-2-3 2.x, dBase IV function as they should?

You should replace the word "will" with the word "are",
because things already work. To avoid lying, I have not
yet tested these particular apps under fdpp+dosemu2,
but I already tested them under freedos+dosemu2, which
is also a 64bit environment after all, but runs more code
in v86 than to stay comfortable with. Since I suppose the
fdpp is a functional equivalent to freedos, I think they will
keep working under fdpp, but I'll do the testing to make
sure.

**Comment by cuzintone** [comment]
stsp, reach out to me offline, i'll try to bring all this together for you. I will also send it to Mercury and Maarten too.

**Comment by stsp** [comment]
My e-mail is github's account name _at_ `list.ru`.
But I am only interested in a technical discussion.
I.e. you may provide more details why you are
not interested in my project, and I'll only have
the choice to either play "marketing" and convincing
you otherwise, or accept that you don't need it.
Both things I already did. :) And it contradicted
my original intention to only ponder the grounds.
The deviation was caused by a huge level of
scepticism, so I had to apply some marketing.
But this isn't going to happen again. :)

**Comment by stsp** [comment]
> C source code of the FreeDOS kernel and duplicating its algorithmic logic in Assembly.

Yeah, but I just don't think that @cuzintone meant
the same thing, and from his doc its still unclear to
me if he did. I.e. it seems to be saying very few, if
at all, about where is the DOS subsystem itself.

**Comment by cuzintone** [comment]
You don't need FreeDOS code to be a replacement OS. Digital Research's DR-DOS contained no code from Microsoft, just an understanding of the underlying API and it worked equally as well (for DOS applications) as the Microsoft version. 

The main entry point of DOS is the Int 21h vector and to a certain extent, the Int 2Fh vector. If a well behaved DOS application is writing to the console, it would probably use INT 21h/02h or maybe Int 21h/09h (the latter is a string function). The VMM would simply trap Int 21h calls and map them to the equivalent NightKernel calls. I mentioned that to Mercury as I didn't see (and I still don't see) an obvious need to use the sources for the FreeDOS kernel in pure form in this project. At it's core, the kernel would be the low level "glue" that links the IO supervisor which handles input/output from hardware devices (the diagram was incomplete; it actually still need some updates) 

The IO Supervisor "should" via the DOS VM trap direct hardware access (which would probably cause a fault) and virtualize and provide the information to the application. 

Now, that isn't to say that you can't use the FreeDOS kernel code, but it would have to be modified in great detail and given Mercury's level of detail in assembly, he's probably going to rewrite the whole thing anyway, which lends to MY premise that it won't be used.

**Comment by stsp** [comment]
> The VMM would simply trap Int 21h calls and map them to the equivalent NightKernel calls.

So VMM is not a part of the ring-0 kernel, right?
Is it in ring-3? It then doesn't need to be in assembly, sure?

**Comment by stsp** [comment]
https://groups.google.com/d/msg/night-dos-kernel/mGh4lDHSISo/P9X4ePgfDAAJ
```
If NightDOS is built properly, the DOS support would be an add-in module that you can just not include. If you look at the diagram I sent, DOS applications make calls to the DOS VM, which in turn calls the NightDOS kernel. If the DOS VM is removed, there should be no side effects other than not having the ability to run DOS software natively. 

This is the best way to build an OS (modular) because components can be linked in (via an API, or drivers) and removed without a lot of work.
```

**Comment by stsp** [comment]
> The IO Supervisor "should" via the DOS VM trap direct hardware access (which would probably
> cause a fault) and virtualize and provide the information to the application.

Which means the DOSish NIC and USB drivers won't work? Or?

**Comment by cuzintone** [comment]
In the original plan, NIghtKernel was going to be NightDOS, a full fledged OS. The DOS support was going to be a swappable component; at some point, the focus changed to just being a kernel. Basically, something along the lines of OS/2

> https://groups.google.com/d/msg/night-dos-kernel/mGh4lDHSISo/P9X4ePgfDAAJ
> 
> ```
> If NightDOS is built properly, the DOS support would be an add-in module
> that you can just not include.
> If you look at the diagram I sent, DOS applications make calls to the DOS VM,
> which in turn calls the
> NightDOS kernel. If the DOS VM is removed, there should be no side effects
> other than not having the ability
> to run DOS software natively. 
> 
> This is the best way to build an OS (modular) because components can be
> linked in (via an API, or drivers)
> and removed without a lot of work.
> ```

Now for your second question, the DOS VMs (individual applications) would run in Ring 3, each application (during the initial discussion) would run separately. The VMM runs ring 0.

**Comment by stsp** [comment]
> In the original plan, NIghtKernel was going to be NightDOS, a full fledged OS.
> The DOS support was going to be a swappable component; at some point, the
> focus changed to just being a kernel.

I would understand that move if it would lead to
some benefits, like USB/NIC DOS drivers working.
As you are still going to virtualize the IO, the only
"advantage" for you is to not use my project. :)
I can think of only 2 possible designs:
- virtualize I/O, do multitasking and all that, but reduce
compatibility to not support DOS drivers and VCPI.
VMM on ring 3. This is by no means a freedos
replacement, this is a dosemu2 at the end.
- go kernel-only, allow direct HW access, perfect
compatibility (maybe up to the point of being a
drop-in freedos replacement, which I seriously doubt)
but no modern features like multitasking etc.

As you are at the process of writing specs, I am
just throwing a material for writing. Would be nice
to read the advantages of the design you code.

**Comment by cuzintone** [comment]
> > The IO Supervisor "should" via the DOS VM trap direct hardware access (which would probably
> > cause a fault) and virtualize and provide the information to the application.
> 
> Which means the DOSish NIC and USB drivers won't work? Or?

A lot of this still hasn't been fully discussed and written. Also, the focus changed quite a bit over the course of the project. If you look at what is written so far (code), there is a basic kernel that goes in to PM and has the very primitive drivers.

To be clear, I am not the owner of the project, but I am trying to answer questions. You have brought a lot of questions to the forefront of this project that I think needed to be answered but hadn't been thought about since coding began in earnest.

**Comment by stsp** [comment]
VCPI is also a big limiting factor in a design
decisions. There are various work-arounds
for the DOSish drivers problem, but VCPI is
very hard to support on a multitasking kernel.
At least if you want to support the pre-VTX hw.

**Comment by mercury0x000d** [comment]
If there's no further commentary or questions on this topic, I suggest we mark it closed. Thoughts?
